"use client";
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';

const fields=['ID','Employee Name','Team1','Date','Profile','Price',"Client's Name",'Order ID','Order Link','Sheet Link','Assign Person','Team','Status','Service Line','Delivery Date','Delivery Amount','Deli_Last_Time','Deadline','Odoo Update','Remarks'];
const emptyOrder=Object.fromEntries(fields.map(f=>[f,'']));
const clean=(v='')=>String(v??'').replace(/\u00A0/g,' ').trim();
function getField(o,...names){if(!o)return'';for(const n of names)if(o[n]!==undefined)return o[n];const ns=names.map(n=>clean(n).toLowerCase());const k=Object.keys(o).find(k=>ns.includes(clean(k).toLowerCase()));return k?o[k]:''}
function money(v){const n=Number(String(v||0).replace(/[^0-9.-]/g,''));return Number.isFinite(n)?'$'+n.toLocaleString(undefined,{maximumFractionDigits:2}):'$0'}
function normStatus(v=''){return clean(v).toLowerCase()}
function statusClass(v=''){const s=normStatus(v);if(s.includes('deliver'))return'delivered';if(s.includes('cancel'))return'cancelled';if(s==='nra'||s.includes('review'))return'review';if(s==='wip')return'wip';return'pending'}
function deadlineNum(v){const t=clean(v).toLowerCase();if(!t||t.includes('done')||t.includes('cancel'))return 9999;if(t.includes('late'))return 0;const m=t.match(/\d+/);return m?Number(m[0]):9999}
function parseDate(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d}
function monthKey(v){const d=parseDate(v);return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`:''}
function monthLabel(v){if(!v)return'All Months';const[y,m]=v.split('-');return new Date(Number(y),Number(m)-1,1).toLocaleDateString(undefined,{month:'long',year:'numeric'})}
function unique(values){return [...new Set(values.map(clean).filter(Boolean))].sort()}
function includesSelected(value,selected){return !selected.length||selected.includes(clean(value))}

export default function DashboardClient({user}){
 const router=useRouter(); const isAdmin=String(user.role).toLowerCase()==='admin';
 const[orders,setOrders]=useState([]);const[activities,setActivities]=useState([]);const[users,setUsers]=useState([]);const[loading,setLoading]=useState(true);const[view,setView]=useState('Dashboard');const[mobile,setMobile]=useState(false);const[query,setQuery]=useState('');
 const[mainTeams,setMainTeams]=useState([]);const[departments,setDepartments]=useState([]);const[statuses,setStatuses]=useState([]);const[services,setServices]=useState([]);const[months,setMonths]=useState([]);const[deliveryDate,setDeliveryDate]=useState('');
 const[modal,setModal]=useState(null);const[form,setForm]=useState(emptyOrder);const[toast,setToast]=useState('');const[installPrompt,setInstallPrompt]=useState(null);const[syncedAt,setSyncedAt]=useState(null);const[profile,setProfile]=useState(user);
 const interval=Number(process.env.NEXT_PUBLIC_SYNC_INTERVAL_MS||10000);

 async function load(silent=false){if(!silent)setLoading(true);try{const calls=[fetch('/api/orders',{cache:'no-store'}),fetch('/api/activity',{cache:'no-store'}),fetch('/api/profile',{cache:'no-store'})];if(isAdmin)calls.push(fetch('/api/admin/users',{cache:'no-store'}));const res=await Promise.all(calls);const od=await res[0].json(),ad=await res[1].json(),pd=await res[2].json();if(res[0].ok){setOrders(od.orders||[]);setSyncedAt(od.syncedAt)}if(res[1].ok)setActivities(ad.activities||[]);if(res[2].ok)setProfile(pd.user||user);if(isAdmin&&res[3]?.ok){const ud=await res[3].json();setUsers(ud.users||[])}}catch(e){showToast('Could not sync data')}finally{if(!silent)setLoading(false)}}
 useEffect(()=>{load();const id=setInterval(()=>load(true),Math.max(interval,5000));const vis=()=>document.visibilityState==='visible'&&load(true);const ins=e=>{e.preventDefault();setInstallPrompt(e)};document.addEventListener('visibilitychange',vis);window.addEventListener('beforeinstallprompt',ins);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',vis);window.removeEventListener('beforeinstallprompt',ins)}},[]);
 function showToast(t){setToast(t);setTimeout(()=>setToast(''),2500)}

 const options=useMemo(()=>({
   mainTeams:unique(orders.map(o=>getField(o,'Team1'))),
   departments:unique(orders.map(o=>getField(o,'Team'))),
   statuses:unique(orders.map(o=>getField(o,'Status'))),
   services:unique(orders.map(o=>getField(o,'Service Line'))),
   months:[...new Set(orders.map(o=>monthKey(getField(o,'Date'))).filter(Boolean))].sort().reverse()
 }),[orders]);
 const filtered=useMemo(()=>orders.filter(o=>{const text=Object.values(o).join(' ').toLowerCase();if(query&&!text.includes(query.toLowerCase()))return false;if(!includesSelected(getField(o,'Team1'),mainTeams))return false;if(!includesSelected(getField(o,'Team'),departments))return false;if(!includesSelected(getField(o,'Status'),statuses))return false;if(!includesSelected(getField(o,'Service Line'),services))return false;if(months.length&&!months.includes(monthKey(getField(o,'Date'))))return false;if(deliveryDate){const d=parseDate(getField(o,'Delivery Date'));if(!d)return false;const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;if(k!==deliveryDate)return false}return true}),[orders,query,mainTeams,departments,statuses,services,months,deliveryDate]);

 const stats=useMemo(()=>filtered.reduce((a,o)=>{a.total++;const s=normStatus(getField(o,'Status'));if(s.includes('deliver')){a.delivered++;const amount=Number(String(getField(o,'Delivery Amount','Delivery Amount(-20%)')||0).replace(/[^0-9.-]/g,''));if(Number.isFinite(amount))a.deliveredAmount+=amount}else if(s==='wip')a.wip++;else if(s.includes('cancel'))a.cancelled++;else if(s==='nra')a.nra++;else if(!s)a.blank++;else a.other++;const price=Number(String(getField(o,'Price')||0).replace(/[^0-9.-]/g,''));if(Number.isFinite(price))a.totalValue+=price;return a},{total:0,delivered:0,wip:0,cancelled:0,nra:0,blank:0,other:0,totalValue:0,deliveredAmount:0}),[filtered]);
 const target=Number(profile?.monthlyTarget||1100);const targetPct=Math.min(100,target?Math.round((stats.deliveredAmount/target)*100):0);const remaining=Math.max(0,target-stats.deliveredAmount);
 const upcoming=filtered.filter(o=>deadlineNum(getField(o,'Deadline'))<=14).length;const deadlines=[...filtered].filter(o=>deadlineNum(getField(o,'Deadline'))<9999).sort((a,b)=>deadlineNum(getField(a,'Deadline'))-deadlineNum(getField(b,'Deadline'))).slice(0,5);

 function resetFilters(){setQuery('');setMainTeams([]);setDepartments([]);setStatuses([]);setServices([]);setMonths([]);setDeliveryDate('')}
 async function save(e){e.preventDefault();const isEdit=modal?.type==='edit';const r=await fetch(isEdit?`/api/orders/${modal.row}`:'/api/orders',{method:isEdit?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)return showToast(d.error||'Save failed');setModal(null);showToast(isEdit?'Order updated':'Order added');load(true)}
 function openAdd(){if(!isAdmin)return;setForm({...emptyOrder,Date:new Date().toISOString().slice(0,10),Status:'WIP','Odoo Update':'No'});setModal({type:'add'})}
 function openEdit(o){if(!isAdmin)return;const c={...emptyOrder};fields.forEach(f=>c[f]=getField(o,f)??'');setForm(c);setModal({type:'edit',row:o._rowNumber})}
 async function remove(o){if(!isAdmin||!confirm(`Delete order ${getField(o,'Order ID')||getField(o,'ID')}?`))return;const r=await fetch(`/api/orders/${o._rowNumber}`,{method:'DELETE'});if(r.ok){showToast('Order deleted');load(true)}else showToast('Delete failed')}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});router.push('/login');router.refresh()}
 async function install(){if(!installPrompt)return showToast('Use the browser Install App option.');installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null)}
 function exportCsv(){const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const csv=[fields.map(esc).join(','),...filtered.map(o=>fields.map(f=>esc(getField(o,f))).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='orderhub-orders.csv';a.click();URL.revokeObjectURL(a.href)}

 const renderFilters=()=> <div className="filters multiFilters"><input placeholder="⌕ Search client, order ID, profile..." value={query} onChange={e=>setQuery(e.target.value)}/>{isAdmin&&<><MultiSelect label="Main Team" options={options.mainTeams} value={mainTeams} onChange={setMainTeams}/><MultiSelect label="Department" options={options.departments} value={departments} onChange={setDepartments}/></>}<MultiSelect label="Status" options={options.statuses} value={statuses} onChange={setStatuses}/><MultiSelect label="Service Line" options={options.services} value={services} onChange={setServices}/><MultiSelect label="Month" options={options.months} value={months} onChange={setMonths} format={monthLabel}/><input type="date" value={deliveryDate} onChange={e=>setDeliveryDate(e.target.value)}/><button className="btn" onClick={resetFilters}>Reset</button></div>;

 const renderTable=()=> <div className="panel ordersPanel"><div className="panelHead"><div><h2>{isAdmin?'All Orders':'My Orders'}</h2><p>Showing {filtered.length} of {orders.length} accessible Google Sheet orders.</p></div><div className="headActions"><button className="btn" onClick={exportCsv}>⇩ Export</button>{isAdmin&&<button className="primaryBtn" onClick={openAdd}>＋ Add New Order</button>}</div></div>{renderFilters()}<div className="tableWrap"><table><thead><tr><th>ID</th><th>Employee Name</th>{isAdmin&&<><th>Main Team</th><th>Department</th></>}<th>Client</th><th>Service Line</th><th>Price</th><th>Status</th><th>Delivery Date</th><th>Delivery Amount</th><th>Deadline</th>{isAdmin&&<th>Actions</th>}</tr></thead><tbody>{filtered.map((o,i)=><tr key={`${o._rowNumber}-${i}`}><td>{getField(o,'ID')}</td><td><div className="employeeCell"><span className="miniAvatar">{(getField(o,'Employee Name')||'?').charAt(0)}</span><div>{getField(o,'Employee Name')}<div className="sub">{getField(o,'Profile')}</div></div></div></td>{isAdmin&&<><td>{getField(o,'Team1')||'-'}</td><td>{getField(o,'Team')||'-'}</td></>}<td>{getField(o,"Client's Name")}</td><td><span className={`tag service s${i%4}`}>{getField(o,'Service Line')}</span></td><td>{money(getField(o,'Price'))}</td><td><span className={`tag ${statusClass(getField(o,'Status'))}`}>● {getField(o,'Status')||'Blank'}</span></td><td>{getField(o,'Delivery Date')||'-'}</td><td>{money(getField(o,'Delivery Amount','Delivery Amount(-20%)'))}</td><td className={deadlineNum(getField(o,'Deadline'))<=4?'deadlineRed':''}>{getField(o,'Deadline')||'-'}</td>{isAdmin&&<td><div className="actions"><button className="iconBtn" onClick={()=>getField(o,'Order Link')&&window.open(getField(o,'Order Link'),'_blank')}>◉</button><button className="iconBtn" onClick={()=>openEdit(o)}>✎</button><button className="iconBtn" onClick={()=>remove(o)}>⋯</button></div></td>}</tr>)}</tbody></table>{!filtered.length&&<div className="empty">No matching orders found.</div>}</div></div>;

 function dashboard(){return <><div className="welcome"><div><h1>Good {new Date().getHours()<12?'Morning':new Date().getHours()<18?'Afternoon':'Evening'}, {profile?.name||user.name}</h1><p>{isAdmin?'Live team performance from your Google Sheet.':'Your personal orders, deliveries and monthly target.'}</p></div><div className="dateText">▣ {new Date().toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'})}</div></div>
 <div className="kpis"><KPI icon="◇" value={stats.total} label={isAdmin?'Total Orders':'My Orders'}/><KPI icon="✓" value={stats.delivered} label="Delivered"/><KPI icon="◷" value={stats.wip} label="WIP"/><KPI icon="✕" value={stats.cancelled} label="Cancelled"/><KPI icon="N" value={stats.nra} label="NRA"/><KPI icon="$" value={money(stats.deliveredAmount)} label="Delivered Amount"/>{isAdmin&&<KPI icon="$" value={money(stats.totalValue)} label="Total Order Value"/>}<KPI icon="⌛" value={upcoming} label="Upcoming Deadlines"/></div>
 {!isAdmin&&<div className="panel targetPanel"><div className="targetTop"><div><span className="eyebrow">MONTHLY DELIVERY TARGET</span><h2>{money(stats.deliveredAmount)} <small>of {money(target)}</small></h2></div><div className="targetNumbers"><b>{targetPct}%</b><span>{money(remaining)} remaining</span></div></div><div className="progressTrack"><div className="progressFill" style={{width:`${targetPct}%`}}/></div><div className="targetMeta"><span>{stats.delivered} delivered orders</span><span>Target: {money(target)}</span></div></div>}
 {renderTable()}<div className="bottomGrid"><StatusPanel stats={stats}/><div className="panel smallPanel"><h3>Upcoming Deadlines</h3>{deadlines.map(o=><div className="deadlineRow" key={o._rowNumber}><b>{getField(o,'ID')}</b><span>{getField(o,"Client's Name")}</span><span className={deadlineNum(getField(o,'Deadline'))<=4?'deadlineRed':''}>{getField(o,'Deadline')}</span></div>)}{!deadlines.length&&<div className="empty compact">No upcoming deadlines.</div>}</div><div className="panel smallPanel"><h3>Recent Activities</h3>{activities.slice(0,5).map((a,i)=><div className="activityRow" key={a._id||i}><span className="activityIcon">{a.source==='Google Sheet'?'▦':'✓'}</span><span>{a.action==='CREATE'?'New order added':`${a.field||'Order'} changed`}<b>{a.orderId&&` #${a.orderId}`}</b><div className="sub">by {a.actorName||a.actorEmail||'Unknown'} · {a.source}</div></span><small>{timeAgo(a.createdAt)}</small></div>)}{!activities.length&&<div className="empty compact">No activity yet.</div>}</div></div></>}

 function activityView(){return <><div className="viewHeader"><div><h1>Activity Log</h1><p className="muted">{isAdmin?'All tracked changes.':'Your tracked changes.'}</p></div><span className="syncPill"><i className="syncDot"/> Auto sync</span></div><div className="panel activityPageList">{activities.map((a,i)=><div className="activityCard" key={a._id||i}><div><b>{a.actorName||a.actorEmail||'Unknown'} · {a.source}</b><p>{a.orderId&&`Order ${a.orderId} · `}{a.field}: “{a.oldValue||'—'}” → “{a.newValue||'—'}”</p></div><small>{new Date(a.createdAt).toLocaleString()}</small></div>)}</div></>}

 function reports(){const rate=Math.round((stats.delivered/Math.max(stats.total,1))*100);return <><div className="viewHeader"><div><h1>{isAdmin?'Reports':'My Performance'}</h1><p className="muted">Current filtered performance.</p></div></div><div className="compactCards"><Stat v={stats.total} l="Orders"/><Stat v={stats.delivered} l="Delivered"/><Stat v={stats.cancelled} l="Cancelled"/><Stat v={stats.nra} l="NRA"/><Stat v={money(stats.deliveredAmount)} l="Delivered Amount"/><Stat v={`${rate}%`} l="Delivered Rate"/></div></>}

 function profileView(){return <><div className="viewHeader"><div><h1>Profile</h1><p className="muted">Account and Google Sheet identity.</p></div></div><div className="pageGrid"><div className="panel profileCard"><ProfilePhoto user={profile}/><h2>{profile?.name}</h2><p>{profile?.email}</p><span className="rolePill">{profile?.role}</span></div><ProfileEditor profile={profile} onSaved={u=>{setProfile(u);showToast('Profile updated')}}/></div></>}

 function userManagement(){if(!isAdmin)return null;return <><div className="viewHeader"><div><h1>User Management</h1><p className="muted">Link users to Sheet names and set monthly targets.</p></div></div><div className="panel userTable"><table><thead><tr><th>User</th><th>Sheet Name</th><th>Target</th><th>Role</th><th>Save</th></tr></thead><tbody>{users.map(u=><AdminUserRow key={u._id} user={u} onSaved={load}/>)}</tbody></table>{!users.length&&<div className="empty">No MongoDB users yet.</div>}</div></>}

 function settings(){return <><div className="viewHeader"><div><h1>Settings</h1><p className="muted">Connection, PWA and account information.</p></div></div><div className="pageGrid"><div className="panel settingsBox"><h3>Google Sheet Sync</h3><p className="muted">Refreshes every {Math.round(interval/1000)} seconds.</p><p>Loaded accessible rows: <b>{orders.length}</b></p><p className="muted">Last sync: {syncedAt?new Date(syncedAt).toLocaleTimeString():'—'}</p></div><div className="panel settingsBox"><h3>Installable App</h3><p className="muted">Install OrderHub from supported browsers.</p><button className="primaryBtn" onClick={install}>Install OrderHub</button></div></div></>}

 const nav=isAdmin?['Dashboard','Orders','Add New Order','Reports','Activity Log','Users','Profile','Settings']:['Dashboard','My Orders','My Performance','Activity Log','Profile','Settings'];
 return <div className="appShell"><div className={`mobileOverlay ${mobile?'show':''}`} onClick={()=>setMobile(false)}/><aside className={`sidebar ${mobile?'open':''}`}><div className="logoRow"><span className="logoIcon">◆</span><div><b>OrderHub</b><small>Work. Track. Deliver.</small></div></div><div className="nav">{nav.map(n=><button className={view===n?'active':''} key={n} onClick={()=>{if(n==='Add New Order')openAdd();else setView(n);setMobile(false)}}><span className="navIcon">{navIcon(n)}</span>{n}</button>)}</div><div className="sidebarBottom"><b>{isAdmin?'👑 Admin Control':'🎯 My Performance'}</b><p>{isAdmin?'Manage teams, users and delivery performance.':`Monthly target ${money(target)}`}</p></div></aside><main className="main"><header className="topbar"><button className="mobileMenuBtn" onClick={()=>setMobile(true)}>☰</button><div className="globalSearch"><span>⌕</span><input placeholder="Search orders, clients, order ID..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="userTop">{installPrompt&&<button className="installBtn" onClick={install}>＋ Install App</button>}<ProfilePhoto user={profile} small/><div className="userText"><b>{profile?.name||user.name}</b><small>{profile?.role||user.role}</small></div><button className="iconBtn" title="Sign out" onClick={logout}>↪</button></div></header>{loading&&<div className="loadingBar"/>}<section className="content">{view==='Dashboard'?dashboard():view==='Orders'||view==='My Orders'?<><div className="viewHeader"><div><h1>{isAdmin?'Orders':'My Orders'}</h1><p className="muted">Live data from Google Sheet.</p></div></div>{renderTable()}</>:view==='Reports'||view==='My Performance'?reports():view==='Activity Log'?activityView():view==='Users'?userManagement():view==='Profile'?profileView():settings()}</section></main>{modal&&<OrderModal modal={modal} form={form} setForm={setForm} save={save} close={()=>setModal(null)} options={options}/>} {toast&&<div className="toast">{toast}</div>}</div>
}

function navIcon(n){return({Dashboard:'⌂',Orders:'▣','My Orders':'▣','Add New Order':'＋',Reports:'▥','My Performance':'▥','Activity Log':'◴',Users:'♙',Profile:'●',Settings:'⚙'})[n]||'•'}
function KPI({icon,value,label}){return <div className="kpi"><div className="kpiIcon">{icon}</div><div><strong>{value}</strong><span>{label}</span></div></div>}
function Stat({v,l}){return <div className="panel statCard"><strong>{v}</strong><span>{l}</span></div>}
function StatusPanel({stats}){return <div className="panel smallPanel"><h3>Order Status Overview</h3><div className="statusBig"><b>{stats.total}</b><span>filtered orders</span></div><div className="legend"><Legend c="#12b76a" n="Delivered" v={stats.delivered}/><Legend c="#fdb022" n="WIP" v={stats.wip}/><Legend c="#f04438" n="Cancelled" v={stats.cancelled}/><Legend c="#2e90fa" n="NRA" v={stats.nra}/><Legend c="#98a2b3" n="Blank" v={stats.blank}/>{stats.other>0&&<Legend c="#667085" n="Other" v={stats.other}/>}</div></div>}
function Legend({c,n,v}){return <div className="legendRow"><span><i className="dot" style={{background:c}}/>{n}</span><b>{v}</b></div>}
function ProfilePhoto({user,small=false}){const cls=small?'profilePhoto small':'profilePhoto';return user?.picture?<img className={cls} src={user.picture} alt="Profile" referrerPolicy="no-referrer"/>:<span className={`${cls} fallback`}>{(user?.name||'U').charAt(0)}</span>}

function MultiSelect({label,options,value,onChange,format=x=>x}){const[open,setOpen]=useState(false);function toggle(v){onChange(value.includes(v)?value.filter(x=>x!==v):[...value,v])}return <div className="multiSelect"><button type="button" className="multiTrigger" onClick={()=>setOpen(!open)}>{value.length?`${label} (${value.length})`:`All ${label}`}<span>⌄</span></button>{open&&<div className="multiMenu"><div className="multiActions"><button type="button" onClick={()=>onChange(options)}>Select all</button><button type="button" onClick={()=>onChange([])}>Clear</button></div>{options.map(o=><label key={o}><input type="checkbox" checked={value.includes(o)} onChange={()=>toggle(o)}/><span>{format(o)}</span></label>)}</div>}</div>}

function OrderModal({modal,form,setForm,save,close,options}){const f=(k,l=k,t='text')=><label>{l}<input type={t} value={form[k]??''} onChange={e=>setForm(x=>({...x,[k]:e.target.value}))}/></label>;return <div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={save}><div className="modalHead"><h2>{modal.type==='edit'?'Edit Order':'Add New Order'}</h2><button type="button" className="iconBtn" onClick={close}>✕</button></div><div className="modalBody"><div className="formGrid">{f('ID')}{f('Employee Name')}<SelectField label="Main Team" value={form.Team1} options={options.mainTeams} onChange={v=>setForm(x=>({...x,Team1:v}))}/>{f('Date','Date','date')}{f('Profile')}{f('Price','Price','number')}{f("Client's Name")}{f('Order ID')}{f('Order Link','Order Link','url')}{f('Sheet Link','Sheet Link','url')}{f('Assign Person')}<SelectField label="Department" value={form.Team} options={options.departments} onChange={v=>setForm(x=>({...x,Team:v}))}/><SelectField label="Status" value={form.Status} options={options.statuses} onChange={v=>setForm(x=>({...x,Status:v}))}/><SelectField label="Service Line" value={form['Service Line']} options={options.services} onChange={v=>setForm(x=>({...x,'Service Line':v}))}/>{f('Delivery Date','Delivery Date','date')}{f('Delivery Amount')}{f('Deli_Last_Time','Last Delivery')}{f('Deadline')}<SelectField label="Odoo Update" value={form['Odoo Update']} options={['Yes','No']} onChange={v=>setForm(x=>({...x,'Odoo Update':v}))}/><label className="full">Remarks<textarea rows="3" value={form.Remarks||''} onChange={e=>setForm(x=>({...x,Remarks:e.target.value}))}/></label></div></div><div className="modalFoot"><button type="button" className="btn" onClick={close}>Cancel</button><button className="primaryBtn">{modal.type==='edit'?'Save Changes':'Add Order'}</button></div></form></div>}
function SelectField({label,value,options,onChange}){return <label>{label}<select value={value||''} onChange={e=>onChange(e.target.value)}><option value="">Select</option>{options.map(x=><option key={x} value={x}>{x}</option>)}</select></label>}

function ProfileEditor({profile,onSaved}){const[name,setName]=useState(profile?.name||'');const[sheetName,setSheetName]=useState(profile?.sheetName||'');const[busy,setBusy]=useState(false);async function save(){setBusy(true);const r=await fetch('/api/profile',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({name,sheetName})});const d=await r.json();setBusy(false);if(r.ok)onSaved(d.user)}return <div className="panel settingsBox"><h3>Personal settings</h3><label className="stackLabel">Display name<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="stackLabel">Google Sheet employee / assign name<input value={sheetName} onChange={e=>setSheetName(e.target.value)}/></label><p className="muted">Your orders are matched using this Sheet name.</p><button className="primaryBtn" onClick={save} disabled={busy}>{busy?'Saving...':'Save profile'}</button></div>}
function AdminUserRow({user,onSaved}){const[sheetName,setSheetName]=useState(user.sheetName||'');const[target,setTarget]=useState(user.monthlyTarget||1100);const[role,setRole]=useState(user.role||'User');const[busy,setBusy]=useState(false);async function save(){setBusy(true);await fetch('/api/admin/users',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:user._id,sheetName,monthlyTarget:target,role})});setBusy(false);onSaved(true)}return <tr><td><div className="employeeCell"><ProfilePhoto user={user} small/><div>{user.name}<div className="sub">{user.email}</div></div></div></td><td><input value={sheetName} onChange={e=>setSheetName(e.target.value)}/></td><td><input type="number" min="0" value={target} onChange={e=>setTarget(e.target.value)}/></td><td><select value={role} onChange={e=>setRole(e.target.value)}><option>User</option><option>Admin</option></select></td><td><button className="btn" onClick={save} disabled={busy}>{busy?'...':'Save'}</button></td></tr>}
function timeAgo(v){if(!v)return'';const s=Math.floor((Date.now()-new Date(v))/1000);if(s<60)return'just now';if(s<3600)return`${Math.floor(s/60)}m ago`;if(s<86400)return`${Math.floor(s/3600)}h ago`;return`${Math.floor(s/86400)}d ago`}
