export const initialDemoOrders = [
  {ID:'23061','Employee Name':'Ibrahim',Team1:'CLA_Team',Date:'2026-09-15',Profile:'bold_brushes',Price:'1000',"Client's Name":'paigemingo','Order ID':'FO1E0C434E43','Order Link':'https://www.fiverr.com/orders/FO1E0C434E43/activities','Sheet Link':'','Assign Person':'Ibrahim',Team:'CT',Status:'WIP','Service Line':'Wordpress','Delivery Date':'2026-10-13','Delivery Amount':'800','Deli_Last_Time':'2026-10-15',Deadline:'14 Days','Odoo Update':'Yes',Remarks:''},
  {ID:'23062','Employee Name':'Ibrahim',Team1:'CLA_Team',Date:'2026-09-17',Profile:'creative_studio',Price:'450',"Client's Name":'johndoe','Order ID':'FO1DEMO23062','Order Link':'','Sheet Link':'','Assign Person':'Ibrahim',Team:'CG',Status:'Delivered','Service Line':'Architecture','Delivery Date':'2026-09-20','Delivery Amount':'360','Deli_Last_Time':'2026-09-20',Deadline:'Order Done','Odoo Update':'Yes',Remarks:'Completed'},
  {ID:'23063','Employee Name':'Rony Ahmed',Team1:'CT_Team',Date:'2026-09-18',Profile:'pixel_craft',Price:'320',"Client's Name":'mikecart','Order ID':'FO1DEMO23063','Order Link':'','Sheet Link':'','Assign Person':'Rony',Team:'AU',Status:'Cancelled','Service Line':'CAD Design','Delivery Date':'2026-09-18','Delivery Amount':'0','Deli_Last_Time':'',Deadline:'Order Cancelled','Odoo Update':'No',Remarks:''}
];
export const sheetHeaders=['ID','Employee Name','Team1','Date','Profile','Price',"Client's Name",'Order ID','Order Link','Sheet Link','Assign Person','Team','Status','Service Line','Delivery Date','Delivery Amount','Deli_Last_Time','Deadline','Odoo Update','Remarks'];
const demoStore=globalThis.__orderhubDemoStore||(globalThis.__orderhubDemoStore=initialDemoOrders.map((o,i)=>({...o,_rowNumber:i+2})));
export function getDemoOrders(){return demoStore.map(o=>({...o}))}
export function addDemoOrder(order){const row=demoStore.reduce((m,o)=>Math.max(m,Number(o._rowNumber)||1),1)+1;const item={...order,_rowNumber:row};demoStore.push(item);return {...item}}
export function updateDemoOrder(row,patch){const i=demoStore.findIndex(o=>String(o._rowNumber)===String(row));if(i<0)throw new Error('Demo row not found');demoStore[i]={...demoStore[i],...patch};return {...demoStore[i]}}
export function deleteDemoOrder(row){const i=demoStore.findIndex(o=>String(o._rowNumber)===String(row));if(i>=0)demoStore.splice(i,1);return true}
